// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WEB_API_KEY'),
    appId: '1:71383646504:web:a5dedaf6b739e576c8901d',
    messagingSenderId: '71383646504',
    projectId: 'traveljournal-de051',
    authDomain: 'traveljournal-de051.firebaseapp.com',
    storageBucket: 'traveljournal-de051.firebasestorage.app',
    measurementId: 'G-FDEVSEE7X4',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_ANDROID_API_KEY'),
    appId: '1:71383646504:android:709831462c1d0389c8901d',
    messagingSenderId: '71383646504',
    projectId: 'traveljournal-de051',
    storageBucket: 'traveljournal-de051.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_IOS_API_KEY'),
    appId: '1:71383646504:ios:5853e2b1d7e3a1b9c8901d',
    messagingSenderId: '71383646504',
    projectId: 'traveljournal-de051',
    storageBucket: 'traveljournal-de051.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_MACOS_API_KEY'),
    appId: '1:71383646504:ios:5853e2b1d7e3a1b9c8901d',
    messagingSenderId: '71383646504',
    projectId: 'traveljournal-de051',
    storageBucket: 'traveljournal-de051.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_WINDOWS_API_KEY'),
    appId: '1:71383646504:web:c122ae10c7848550c8901d',
    messagingSenderId: '71383646504',
    projectId: 'traveljournal-de051',
    authDomain: 'traveljournal-de051.firebaseapp.com',
    storageBucket: 'traveljournal-de051.firebasestorage.app',
    measurementId: 'G-TMBMD7VFL3',
  );
}
